#This is the production workflow

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    command: sh -c "npx prisma db push && npm run start:prod"
    container_name: sacco-backend
    restart: always
    ports:
      - "3001:3000"
    environment:
      - DATABASE_URL=mysql://root:@Bekhan12@mysql:3306/sacco_db
      - PORT=3000
      - SYSTEM_SECRET=MYAUTHSECRETISVERYSTRONG
      - MODE=Prod
      - REDIS_URL=redis://redis:6379
      - EMAIL_USER=anchorwithin069@gmail.com
      - EMAIL_PASS=dvna yfox yvsd lxjg
    volumes:
      - /root/sacco/sacco-assets:/app/uploads
      - /root/sacco/assets:/app/src/assets
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - mysql-redis-network

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - "127.0.0.1:6379:6379"
    networks:
      - mysql-redis-network

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=@Bekhan12
      - MYSQL_DATABASE=sacco_db
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p@Bekhan12"]
    networks:
      - mysql-redis-network

networks:
  mysql-redis-network:
    name: "mysql-redis-network"
    driver: bridge

volumes:
  mysql_data: